# Generated by Django 2.2.16 on 2022-06-10 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220610_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустимые символы: буквы, цифры, +, @, ., -,_', regex='^[\\w.@+-]+$')]),
        ),
    ]
